### PR TITLE
Environment settings refactor

### PR DESCRIPTION
**Pull request by kellpossible**
+ Refactor `phase1-coordinator` `Settings` tuple into a struct.

### CODE REVIEW

**Review by apruden2008 — APPROVED** [review]
These look like sensible changes to me, and make the code a little bit more readable.

**Comment by apruden2008** [comment]
@kellpossible are you still working on these?

**Comment by kellpossible** [comment]
I wasn't sure how welcome these changes would be after some earlier discussions about making unecessary changes to the code, so I left it on the backburner, however if you think this is worthwhile I can resurrect this one

**Comment by apruden2008** [comment]
@kellpossible is this still relevant after the refactors you and Ilya have done?

**Comment by kellpossible** [comment]
@apruden2008 yep still relevant

**Review by ibaryshnikov — APPROVED** [review]
Such a great change! It improves readability a lot.

**Pull request merged**
