### PR TITLE
Coordinator comments refactor

### PR DESCRIPTION
**Pull request by kellpossible**
+ Removes macro `storage!` - it wasn't doing anything special and it breaks IDE refactoring. There are quite a few more macros used in this project that could also be removed... Not worth doing it now though.
+ In `drop_contributor()` use `match` (instead of seperate `if` statements) on on `participant` to ensure at compile time that all participant types are handled.
+ Some documentation for the `Participant` struct.

### CODE REVIEW

**Comment by ibaryshnikov** [comment]
Looks good

**Review by ibaryshnikov — APPROVED** [review]

**Review by apruden2008 — APPROVED** [review]

**Comment by apruden2008** [comment]
Please describe in more detail the changes

**Comment by kellpossible** [comment]
@apruden2008 I've updated the description, this one is ready for review

**Review by apruden2008 — APPROVED** [review]

**Comment by apruden2008** [comment]
@kellpossible take a look and resolve these conflicts and then we can merge

**Pull request merged**
