### PR TITLE
close #83 - provide a way to initialize the console error panic hook

### LINKED ISSUE #83: phase1-wasm doesn't have console_error_panic_hook set up
When I trigger a panic I get the following in the browser console.

```txt
RuntimeError: unreachable
    at __rust_start_panic (http://localhost:8080/35110bd7605535989399.module.wasm:wasm-function[4928]:0x1c9bf6)
    at rust_panic (http://localhost:8080/35110bd7605535989399.module.wasm:wasm-function[4432]:0x1c6801)
    at std::panicking::rust_panic_with_hook::h6c81660583233495 (http://localhost:8080/35110bd7605535989399.module.wasm:wasm-function[1062]:0x175ac9)
    at std::panicking::begin_panic_handler::{{closure}}::h35f4baddc401ed83 (http://localhost:8080/35110bd7605535989399.module.wasm:wasm-function[4250]:0x1c48fb)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h9f9c9a1ba07fa30f (http://localhost:8080/35110bd7605535989399.module.wasm:wasm-function[4268]:0x1c4c3d)
    at rust_begin_unwind (http://localhost:8080/35110bd7605535989399.module.wasm:wasm-function[3821]:0x1bf004)
    at core::panicking::panic_fmt::h29e09648cb9a0a7a (http://localhost:8080/35110bd7605535989399.module.wasm:wasm-function[4270]:0x1c4ca1)
    at core::option::expect_none_failed::hf0424e633716ac95 (http://localhost:8080/35110bd7605535989399.module.wasm:wasm-function[1864]:0x196db5)
    at core::result::Result<T,E>::expect::ha26b22df99b57479 (http://localhost:8080/35110bd7605535989399.module.wasm:wasm-function[1236]:0x17eaf0)
    at phase1_wasm::phase1::Phase1WASM::contribute_chunked::hfccb5296d2ee3d4c (http://localhost:8080/35110bd7605535989399.module.wasm:wasm-function[153]:0x11272f)
```

The reason for the panic is not displayed, I think because https://github.com/rustwasm/console_error_panic_hook has not been correctly instantiated for use with this api.

### PR DESCRIPTION
**Pull request by kellpossible**
Solve #83

### CODE REVIEW

**Review by kobigurk — APPROVED** [review]
LGTM.
@raychu86 / @howardwu - any ideas why the SSH key for snarkOS isn't available?

**Comment by raychu86** [comment]
Do we need the ssh key for snarkOS anymore since it is a public repository now?

**Comment by kobigurk** [comment]
> @kobigurk Do we need the ssh key for snarkOS anymore since it is a public repository now?

Good point, we should remove it.

**Comment by raychu86** [comment]
Though, it should work regardless. Not sure why it isn't available here.

**Review by raychu86 — APPROVED** [review]

**Pull request merged**
