### PR TITLE
phase1-coordinator proptest

### PR DESCRIPTION
**Pull request by kellpossible**

### CODE REVIEW

**Comment by kellpossible** [comment]
With the following command in `phase1-coordinator`: `RUST_BACKTRACE=1 cargo test --features silent --lib -- tests::proptests::coordinator_proptest --exact --nocapture`

I get the following failure:

```
running 1 test
[phase1-coordinator/src/tests/proptests.rs:180] &env_params = Custom(
    (
        Chunked,
        Groth16,
        Bls12_377,
        6,
        15,
        4,
    ),
)
[phase1-coordinator/src/tests/proptests.rs:181] &rounds_params = RoundProptestParams {
    rounds: 2,
    contributors: [
        [
            ParticipantProptestParams {
                reliability_score: 236,
            },
            ParticipantProptestParams {
                reliability_score: 101,
            },
            ParticipantProptestParams {
                reliability_score: 72,
            },
            ParticipantProptestParams {
                reliability_score: 38,
            },
        ],
        [
            ParticipantProptestParams {
                reliability_score: 72,
            },
            ParticipantProptestParams {
                reliability_score: 125,
            },
            ParticipantProptestParams {
                reliability_score: 198,
            },
            ParticipantProptestParams {
                reliability_score: 100,
            },
        ],
    ],
    verifiers: [
        [
            ParticipantProptestParams {
                reliability_score: 106,
            },
            ParticipantProptestParams {
                reliability_score: 133,
            },
        ],
        [
            ParticipantProptestParams {
                reliability_score: 207,
            },
            ParticipantProptestParams {
                reliability_score: 231,
            },
            ParticipantProptestParams {
                reliability_score: 82,
            },
            ParticipantProptestParams {
                reliability_score: 161,
            },
        ],
    ],
}
Computing contributions for round 1 chunk 8 contribution 1, contributor test-contributor-r1i1.contributor
Trying to add contributions for round 1 chunk 8 contribution 1, contributor test-contributor-r1i1.contributor
Computing contributions for round 1 chunk 9 contribution 1, contributor test-contributor-r1i1.contributor
Trying to add contributions for round 1 chunk 9 contribution 1, contributor test-contributor-r1i1.contributor
Computing contributions for round 1 chunk 10 contribution 1, contributor test-contributor-r1i1.contributor
Trying to add contributions for round 1 chunk 10 contribution 1, contributor test-contributor-r1i1.contributor
Computing contributions for round 1 chunk 11 contribution 1, contributor test-contributor-r1i1.contributor
Trying to add contributions for round 1 chunk 11 contribution 1, contributor test-contributor-r1i1.contributor
Computing contributions for round 1 chunk 12 contribution 1, contributor test-contributor-r1i1.contributor
Trying to add contributions for round 1 chunk 12 contribution 1, contributor test-contributor-r1i1.contributor
Computing contributions for round 1 chunk 13 contribution 1, contributor test-contributor-r1i1.contributor
Trying to add contributions for round 1 chunk 13 contribution 1, contributor test-contributor-r1i1.contributor
Computing contributions for round 1 chunk 14 contribution 1, contributor test-contributor-r1i1.contributor
Trying to add contributions for round 1 chunk 14 contribution 1, contributor test-contributor-r1i1.contributor
Computing contributions for round 1 chunk 15 contribution 1, contributor test-contributor-r1i1.contributor
Trying to add contributions for round 1 chunk 15 contribution 1, contributor test-contributor-r1i1.contributor
Computing contributions for round 1 chunk 16 contribution 1, contributor test-contributor-r1i1.contributor
Trying to add contributions for round 1 chunk 16 contribution 1, contributor test-contributor-r1i1.contributor
thread 'tests::proptests::coordinator_proptest' panicked at 'called `Result::unwrap()` on an `Err` value: Error during proptest

Caused by:
    0: Error while contributor test-contributor-r1i1.contributor was making contribution
    1: Error while trying to add contributor test-contributor-r1i1.contributor contribution for round 1 chunk 16 contribution 1
    2: ParticipantMissingPendingTask', phase1-coordinator/src/tests/proptests.rs:128:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   3: core::result::Result<T,E>::unwrap
             at /home/luke/.rustup/toolchains/1.48-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:973
   4: phase1_coordinator::tests::proptests::coordinator_proptest::{{closure}}
             at ./src/tests/proptests.rs:124
   5: core::ops::function::impls::<impl core::ops::function::Fn<A> for &F>::call
             at /home/luke/.rustup/toolchains/1.48-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:237
   6: proptest::test_runner::runner::call_test::{{closure}}
             at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/proptest-0.10.1/src/test_runner/runner.rs:246
   7: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /home/luke/.rustup/toolchains/1.48-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:308
   8: std::panicking::try::do_call
             at /home/luke/.rustup/toolchains/1.48-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:381
   9: __rust_try.llvm.7436213308941010821
  10: std::panicking::try
             at /home/luke/.rustup/toolchains/1.48-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:345
  11: std::panic::catch_unwind
             at /home/luke/.rustup/toolchains/1.48-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:382
  12: proptest::test_runner::runner::call_test
             at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/proptest-0.10.1/src/test_runner/runner.rs:246
  13: proptest::test_runner::runner::TestRunner::run_one_with_replay
             at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/proptest-0.10.1/src/test_runner/runner.rs:693
  14: proptest::test_runner::runner::TestRunner::gen_and_run_case
             at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/proptest-0.10.1/src/test_runner/runner.rs:649
  15: proptest::test_runner::runner::TestRunner::run_in_process_with_replay
             at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/proptest-0.10.1/src/test_runner/runner.rs:602
  16: proptest::test_runner::runner::TestRunner::run_in_process
             at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/proptest-0.10.1/src/test_runner/runner.rs:560
  17: proptest::test_runner::runner::TestRunner::run
             at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/proptest-0.10.1/src/test_runner/runner.rs:403
  18: phase1_coordinator::tests::proptests::coordinator_proptest
             at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/proptest-0.10.1/src/sugar.rs:163
  19: phase1_coordinator::tests::proptests::coordinator_proptest::{{closure}}
             at /home/luke/.cargo/registry/src/github.com-1ecc6299db9ec823/proptest-0.10.1/src/sugar.rs:159
  20: core::ops::function::FnOnce::call_once
             at /home/luke/.rustup/toolchains/1.48-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
  21: core::ops::function::FnOnce::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
```

**Comment by kellpossible** [comment]
The source of the problem is in a call stack like `Coordinator::contribute()` -> `Coordinator::try_contribute()` -> `CoordinatorState::completed_task()` -> `ParticipantInfo::completed_task()`

**Comment by kellpossible** [comment]
This test also ultimately needs to be changed to allow contributors to make contributions in parallel. Same with verifications (I think).

**Comment by apruden2008** [comment]
@kellpossible can you close this and open a new issue for updating the integration test per our discussion this morning? Thank you

**Pull request closed without merging**
