### PR TITLE
Added a binary to generate view key to verifier

### PR DESCRIPTION
**Pull request by ibaryshnikov**

### CODE REVIEW

**Review by kellpossible — APPROVED** [review]
Looks good to me!

**Comment by apruden2008** [comment]
Thanks @ibaryshnikov. What is the justification? How does this help the verifier?

**Comment by ibaryshnikov** [comment]
We need the view key in order to run the verifier. Where are we supposed to get one?

**Review by apruden2008 — APPROVED** [review]
Moving view keys from script inside of the verifier binary makes sense to me

**Comment by apruden2008** [comment]
Merge before #211, so we can prepare for review

**Comment by apruden2008** [comment]
@ilya please add create a separate utilities folder and ensure there is CI integration through Github actions. Thanks!

**Comment by ibaryshnikov** [comment]
Closing in favor of #229

**Pull request closed without merging**
