### PR TITLE
Replaced zexe_algebra with snarkVM

### PR DESCRIPTION
**Pull request by ibaryshnikov**
This branch contains only replacements of the dependencies. No actual code has been changed.
Should work on nightly.

Current concerns about snarkVM:
- no "parallel" feature (similar to "zexe_algebra/parallel")
- EvaluationDomain is a struct instead of a trait
- no Radix2EvaluationDomain

### CODE REVIEW

**Comment by apruden2008** [comment]
@ibaryshnikov what is the status of this?

**Comment by ibaryshnikov** [comment]
Awaiting feedback on missing parts

**Comment by apruden2008** [comment]
@howardwu I believe you are actively working on snarkVM still?

**Comment by apruden2008** [comment]
Per our standup, switch to snarkVM from snarkOS

**Comment by howardwu** [comment]
Closing this in favor of PR #317

**Pull request closed without merging**
